### ISSUE TITLE
Main is not defined

### ISSUE THREAD

**Issue by symonkipkemei** [shadmeoli/Murife_don-t_run#1]
![image](https://user-images.githubusercontent.com/85394343/193194396-715407d1-4450-4efc-8802-cf48630b1a63.png)
Hey there, this is great! 
I tried running Murife from the cli, This is what I encountered.

**Comment by shadmeoli** [comment]
![Uploading Screenshot from 2022-09-30 08-28-15.png…]()
For me I am using pipenv as my version control but it dosen't really matter.
For the it to run you need to make it accessible directly without using the "python" command..
Use " pip install --editable ." to make it a valid command

**Comment by shadmeoli** [comment]
Check out the updated instruction guide is stuck.
